name: Publish

on:
  push:
    branches: [main]

concurrency: publish-${{ github.ref }}

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  publish:
    name: Publish

    needs: [tests]

    runs-on: ubuntu-24.04

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'
      - name: Set up Maven GitHub Packages credentials
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github-packages</id><username>${GITHUB_ACTOR}</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Deploy with Maven
        run: mvn deploy
