name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode test
