name: Tests

on:
  pull_request:
  workflow_call:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/actions/checkout/issues/135#issuecomment-602171132
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode test
